### ISSUE TITLE
When come home, play music?

### ISSUE THREAD

**Issue by JonathanCasey** [JonathanCasey/home-assistant-config#25]
Should be able to add a slight delay, then turn on shield and receiver, set volume, and maybe play something from live jazz station on youtube?

**Comment by JonathanCasey** [comment]
[Totally possible](https://selfhostedhome.com/integrating-nvidia-shield-with-home-assistant/#crayon-5f1c5e6ca5045875058976-24:~:text=Triggering%20YouTube%20Video)

Quoting here:

> Another thing you might want to do is automatically play a YouTube video whenever an event occurs. Maybe during the holidays, you want to come into a house with the classic log fireplace video running.
>
> Well that can easily be achieved by using the adb_command service once again.
>
> This time though we use the view intent action to launch the video. This tells Android TV to open the correct app with the link, which happens to be YouTube.
>
```yaml
service: androidtv.adb_command
entity_id: media_player.living_room_nvidia_shield
command: "am start -a android.intent.action.VIEW https://www.youtube.com/watch?v=GG8LcqR1kqw"
```
>
>The Home Assistant media player integration has lots of other services. Let me know in the comments any automations you’re planning on using with the NVIDIA Shield.
